# Generated by Django 5.2 on 2025-05-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abastecimiento',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='abastecimiento',
            name='estado',
            field=models.CharField(choices=[('Sin reportar', 'Sin Reportar'), ('Reportado', 'Reportado')], default='Sin reportar', max_length=30),
        ),
        migrations.AddField(
            model_name='abastecimiento',
            name='fecha_reporte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumoabastecimiento',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='insumoabastecimiento',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insumoabastecimiento',
            name='estado',
            field=models.CharField(choices=[('Acabado', 'Acabado'), ('Uso medio', 'Uso medio'), ('Bajo', 'Bajo'), ('Sin usar', 'Sin usar')], default='Sin usar', max_length=30),
        ),
    ]
